In [3]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
import pandas as pd

In [10]:
red_df = pd.read_csv('./winequality-red.csv')
redwine_X = red_df.iloc[:,:-1]
redwine_y = red_df.iloc[:,-1]
redwine_y.value_counts()
redwine_y1 = redwine_y-3
redwine_y1.value_counts()

2    681
3    638
4    199
1     53
5     18
0     10
Name: quality, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(redwine_X, redwine_y1,
                                                   test_size=0.3)

In [13]:
model = Sequential()
# 첫번째 h1
model.add(Dense(100, input_shape=(11,), activation='sigmoid')) # input_shape은 features
model.add(Dropout(0.2))

# 두번째 h2
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.4))

# 세번째 h3
model.add(Dense(50, activation='tanh'))
model.add(Dropout(0.1))

# 출력층 정의
model.add(Dense(6, activation='softmax'))


In [14]:
# 학습을 정의한다.

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])


In [15]:
model.fit(X_train,y_train.to_numpy(),
         epochs = 300, batch_size=200)

Epoch 1/300
6/6 [==============================] - 1s 5ms/step - loss: 1.6001 - accuracy: 0.3164
Epoch 2/300
6/6 [==============================] - 0s 4ms/step - loss: 1.3412 - accuracy: 0.4138
Epoch 3/300
6/6 [==============================] - 0s 4ms/step - loss: 1.2575 - accuracy: 0.4540
Epoch 4/300
6/6 [==============================] - 0s 4ms/step - loss: 1.2150 - accuracy: 0.4468
Epoch 5/300
6/6 [==============================] - 0s 4ms/step - loss: 1.2309 - accuracy: 0.4424
Epoch 6/300
6/6 [==============================] - 0s 3ms/step - loss: 1.1957 - accuracy: 0.4727
Epoch 7/300
6/6 [==============================] - 0s 3ms/step - loss: 1.1891 - accuracy: 0.4942
Epoch 8/300
6/6 [==============================] - 0s 4ms/step - loss: 1.1912 - accuracy: 0.4647
Epoch 9/300
6/6 [==============================] - 0s 3ms/step - loss: 1.1858 - accuracy: 0.4576
Epoch 10/300
6/6 [==============================] - 0s 3ms/step - loss: 1.1727 - accuracy: 0.4701
Epoch 11/300
6/6 [===========

6/6 [==============================] - 0s 3ms/step - loss: 1.0256 - accuracy: 0.5585
Epoch 85/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0258 - accuracy: 0.5532
Epoch 86/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0160 - accuracy: 0.5532
Epoch 87/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0250 - accuracy: 0.5567
Epoch 88/300
6/6 [==============================] - 0s 4ms/step - loss: 1.0219 - accuracy: 0.5407
Epoch 89/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0179 - accuracy: 0.5576
Epoch 90/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0104 - accuracy: 0.5782
Epoch 91/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0179 - accuracy: 0.5594
Epoch 92/300
6/6 [==============================] - 0s 3ms/step - loss: 1.0238 - accuracy: 0.5469
Epoch 93/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9881 - accuracy: 0.5630
Epoch 94/300
6/6 [===============

6/6 [==============================] - 0s 3ms/step - loss: 0.9708 - accuracy: 0.5871
Epoch 168/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9796 - accuracy: 0.5746
Epoch 169/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9661 - accuracy: 0.5764
Epoch 170/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9747 - accuracy: 0.5782
Epoch 171/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9533 - accuracy: 0.5782
Epoch 172/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9658 - accuracy: 0.5746
Epoch 173/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9748 - accuracy: 0.5818
Epoch 174/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9570 - accuracy: 0.5800
Epoch 175/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9735 - accuracy: 0.5710
Epoch 176/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9665 - accuracy: 0.5684
Epoch 177/300
6/6 [=====

6/6 [==============================] - 0s 3ms/step - loss: 0.9388 - accuracy: 0.5871
Epoch 250/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9366 - accuracy: 0.5943
Epoch 251/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9315 - accuracy: 0.6050
Epoch 252/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9374 - accuracy: 0.5845
Epoch 253/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9383 - accuracy: 0.5898
Epoch 254/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9283 - accuracy: 0.6041
Epoch 255/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9313 - accuracy: 0.5907
Epoch 256/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9417 - accuracy: 0.5853
Epoch 257/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9356 - accuracy: 0.5898
Epoch 258/300
6/6 [==============================] - 0s 3ms/step - loss: 0.9453 - accuracy: 0.5809
Epoch 259/300
6/6 [=====

In [16]:
model.evaluate(X_test, y_test)

15/15 [==============================] - 0s 1ms/step - loss: 0.9228 - accuracy: 0.5938


[0.9227575659751892, 0.59375]

In [17]:
from sklearn.metrics import classification_report

In [18]:
model.predict(X_test)

15/15 [==============================] - 0s 993us/step


array([[4.1245494e-05, 2.5254930e-03, 1.2031059e-01, 3.2455969e-01,
        4.7843197e-01, 7.4131057e-02],
       [1.3519191e-02, 8.6322054e-02, 4.6393582e-01, 3.6954308e-01,
        6.0136314e-02, 6.5436228e-03],
       [5.2238762e-02, 1.8544909e-01, 5.9710991e-01, 1.5706170e-01,
        7.9870177e-03, 1.5346674e-04],
       ...,
       [2.4121578e-01, 7.3887944e-02, 6.4076287e-01, 4.3613967e-02,
        5.1475893e-04, 4.7724802e-06],
       [1.2474525e-03, 1.8133560e-02, 8.8282633e-01, 9.4407253e-02,
        3.3364336e-03, 4.8990976e-05],
       [2.4898141e-04, 8.3986335e-03, 6.4774007e-02, 3.5590509e-01,
        5.2137411e-01, 4.9299195e-02]], dtype=float32)

In [34]:
pred = np.argmax(model.predict(X_test),axis=1)
pred_y_np = pred+3

15/15 [==============================] - 0s 864us/step


In [33]:
# array2d = np.array([[8,12],
#                    [7,1]])

# sort_array2d_axis0 = np.sort(array2d, axis=0) # 로우
# print('로우 방향으로 정렬: \n', sort_array2d_axis0)

# sort_array2d_axis1 = np.sort(array2d, axis=1) # 컬럼
# print('컬럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


In [38]:
act_y_np = (y_test+3).to_numpy()
pd.crosstab(act_y_np,pred_y_np)

col_0    5   6   7
row_0             
3        1   0   0
4       12   3   1
5      167  35   4
6       82  99  21
7        5  26  19
8        0   1   4