In [1]:
import numpy as np
dy = np.array([[1,2,3],[4,5,6]])
dy

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
db = np.sum(dy, axis = 0)
db

array([5, 7, 9])

In [3]:
db = np.sum(dy, axis = 1)
db

array([ 6, 15])

## 배치용 Affine 계층

In [ ]:
class affine:
    def __init__(self, w, b):
        self.w = w
        self.b = b
        self.x = None
        self.dw = None
        self.db = None
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.w) + self.b
        return out
    def backward(self, dout):
        dx = np.dot(dout, self.w.t)
        self.dw = np.dot(self.x.t, dout)
        self.db = np.sum(dout, axis = 0)
        return dx
        