In [6]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [4]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [7]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [8]:
c = np.max(a)
a - c # overflow 를 방지

array([  0, -10, -20])

In [10]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [11]:
## 오버플로우 대책

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [13]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0


In [38]:
random_weights = np.random.randn(2,4)
random_baises = np.zeros((1,4))
random_weights, random_baises
inputs = np.array([1,2])
ouput = np.dot(inputs, random_weights) + random_biases


In [94]:
class LayerDense:
    def __init__(self, inputs_n, nodes_n):
        self.weights = np.random.randn(inputs_n, nodes_n)
        self.baises = np.zeros((1,nodes_n))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.baises
class ActivationRelu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
class ActivationSoftmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs)
        p = exp_values / np.sum(exp_values)
        self.output = p
        
inputs = np.array([[1, 2],
                   [3, 4]])

dense1 = LayerDense(2, 3)
activation1 = ActivationRelu()
dense1.forward(inputs)
activation1.forward(dense1.output)
print('activation:',activation1.output)

softmax = ActivationSoftmax()
softmax.forward(inputs)
print('softmax:',softmax.output)

activation: [[0.17826072 2.32907988 1.41472328]
 [2.43571085 3.3829287  4.054956  ]]
softmax: [[0.0320586  0.08714432]
 [0.23688282 0.64391426]]


In [81]:
test_output = [4.8, 1.21, 2.385]
exp_values = np.exp(test_output)
norm_values = exp_values/np.sum(exp_values)
norm_values

array([0.89528266, 0.02470831, 0.08000903])

In [95]:
input_data = np.array([1, 2, 3])
dense1 = LayerDense(3, 5)
activation1 = ActivationRelu()
dense2 = LayerDense(5, 5)
activation2 = ActivationSoftmax()
dense1.forward(input_data)

activation1.forward(dense1.output)
dense2.forward(activation1.output)

activation2.forward(dense2.output)
activation2.output

array([[3.65605253e-02, 3.68052789e-05, 4.59452944e-02, 9.17245446e-01,
        2.11928757e-04]])